M48
; DRILL file KiCad 10.0.6 date 2026-10-03T10:19:17
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-03T10:19:17-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.300
%
G90
G05
T1
X127.93Y-110.45
X139.36Y-110.45
T2
X117.7Y-111.75
X117.75Y-67.25
X203.0Y-111.725
X203.75Y-67.25
M30
